#!/bin/bash

# Setup script for deployment configuration
# Creates the necessary configuration files for deploying to AWS

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}=== Obscvrat Deployment Configuration Setup ===${NC}\n"

# Function to prompt for input
prompt_input() {
    local prompt=$1
    local default=$2
    local input
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " input
        echo "${input:-$default}"
    else
        read -p "$prompt: " input
        echo "$input"
    fi
}

# Function to create config file
create_config() {
    local env=$1
    local config_file="$SCRIPT_DIR/.deploy-config.$env"
    
    echo -e "${BLUE}Configuring $env environment...${NC}\n"
    
    local s3_bucket=$(prompt_input "S3 Bucket name" "obscvrat-website")
    local distribution_id=$(prompt_input "CloudFront Distribution ID" "")
    local aws_profile=$(prompt_input "AWS Profile" "default")
    local aws_region=$(prompt_input "AWS Region" "eu-west-1")
    local domain=$(prompt_input "Domain name" "obscvrat.fi")
    
    cat > "$config_file" << EOF
# Deployment configuration for $env environment
# Generated by setup-deploy.sh

S3_BUCKET="$s3_bucket"
DISTRIBUTION_ID="$distribution_id"
AWS_PROFILE="$aws_profile"
AWS_REGION="$aws_region"
DOMAIN="$domain"
EOF
    
    echo -e "${GREEN}✓ Configuration saved to: $config_file${NC}\n"
}

# Main menu
show_menu() {
    echo "Select environment to configure:"
    echo "1) Production (obscvrat.fi)"
    echo "2) Staging (CloudFront testing)"
    echo "3) Both"
    echo "4) Exit"
    echo ""
}

# Main loop
while true; do
    show_menu
    read -p "Enter choice (1-4): " choice
    
    case $choice in
        1)
            create_config "production"
            ;;
        2)
            create_config "staging"
            ;;
        3)
            create_config "production"
            create_config "staging"
            ;;
        4)
            echo -e "${GREEN}Setup complete!${NC}"
            echo ""
            echo "Next steps:"
            echo "1. Review the configuration files in $SCRIPT_DIR"
            echo "2. Test deployment: ./scripts/deploy.sh production --dry-run"
            echo "3. Deploy: ./scripts/deploy.sh production"
            exit 0
            ;;
        *)
            echo -e "${YELLOW}Invalid choice. Please try again.${NC}\n"
            ;;
    esac
done
